title: RWA breakdown
author: Aadi, Jochem, Raul, Victor

execute:
  execute_notebooks: "auto"

html:
  favicon: "figures/favicon.ico"
  baseurl: ""
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    nb_execution_includepatterns:
      - "notebooks/intro.ipynb"
      - "notebooks/chapter1.ipynb"
      - "notebooks/chapter2.ipynb"
      - "notebooks/chapter3.ipynb"
      - "notebooks/chapter4.ipynb"
      - "notebooks/chapter5.ipynb"

    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    html_theme_options:
      repository_url: "https://github.com/jjhvandervliet/test_project"
      use_repository_button: true
      use_issues_button: true
      launch_buttons:
        thebe: true

    html_last_updated_fmt: "%B %-d, %Y"
    html_show_copyright: false

  extra_extensions:
    - sphinx_tudelft_theme

bibtex_bibfiles:
  - references.bib
