title: RWA breakdown
author: Aadi, Jochem, Raul, Victor

execute:
  execute_notebooks: "auto"

html:
  favicon: "figures/favicon.ico"
  baseurl: ""
  use_issues_button: true
  use_repository_button: true
  theme: sphinx_book_theme

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

bibtex_bibfiles:
  - references.bib
