name: call-deploy-book

on:
  push:
    branches:
      - "**"
    paths:
      - book/_config.yml
      - book/_toc.yml
      - book/intro.md
      - book/notebooks/**
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs:
  call-workflow:
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

  deploy:
    needs: call-workflow
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages # This is the typical name used by Jupyter Book artifacts.
          path: ./_site # Download the artifact into a temporary directory named _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Updated to v4 (Recommended)
        with:
          artifact_name: github-pages # Use the same name to point to the downloaded content
