name: call-deploy-book

on:
  push:
    branches:
      - "**"
    paths:
      - book/_config.yml
      - book/_toc.yml
      - book/intro.md
      - book/notebooks/**
      - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

jobs:
  call-workflow:
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@main
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
